name: Build and Push Docker image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: docker-build
        run: echo docker and such
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3

#     - name: Build Docker image
#       run: docker build -t data-validator .

#     - name: (Optional) Run container
#       run: docker run data-validator
